### ISSUE TITLE
Analysisrequest "Add XX ARs" context action not translated

### ISSUE THREAD

**Issue by ramonski** [bikalabs/bika.lims#1984]
## Steps to reproduce

Navigate to the `analysisrequests` view of a specific client.

## Current behavior

It is not possible to translate the context action "Add XX ARs" in the form.

## Expected behavior

It should be possible to translate this.

## Screenshot (optional)

<img width="442" alt="cbg_-_hagen_" src="https://cloud.githubusercontent.com/assets/713193/24079146/bec8ae58-0c81-11e7-9d54-0fe4cd021f9c.png">

**Comment by ramonski** [comment]
<img width="1122" alt="screenshot_19_03_17__08_56" src="https://cloud.githubusercontent.com/assets/713193/24079168/205a261a-0c82-11e7-969a-2e811dbc18fc.png">

**Comment by ramonski** [comment]
Seems like the `t(_(...))` trick prevents the "Add" string to be translated.

@rockfruit:
I still don't know when to use simple `_(...)` and when to do `t(_(...))`. Could you explain one more time?

<img width="781" alt="screenshot_19_03_17__09_09" src="https://cloud.githubusercontent.com/assets/713193/24079258/d46c4376-0c83-11e7-97ae-c3f35614f9c3.png">

**Comment by rockfruit** [comment]
@ramonski t() returns a utf-8 translated string - but it takes an i18n message as it's argument.  _() converts a string to a zope.i18n message.  So if the argument is not yet converted to an i18n message, it must be done before calling t() - and this is something that is not always easy to predict.

**Comment by ramonski** [comment]
Thanks @rockfruit, but in that case we should have already an `i18n` message object, but it keeps untranslated unless I remove the outer `t()` function call. Are there any other side-effects if we remove this as I have done in this PR?
