### ISSUE TITLE
CC contacts not saving during AR creation

### ISSUE THREAD

**Issue by andersonsmith** [bikalabs/bika.lims#1995]
## Steps to reproduce

At AR add screen, select contact that has automatic CC contacts enabled.  CC contacts are added to the form as expected.  Upon creating the AR, the AR view only shows the primary contact and the CC contacts are empty.

## Current behavior

CC contacts are not saving with the AR creation.

## Expected behavior

CC contacts are saved during creation.

## Screenshot (optional)

![ar add screen](https://cloud.githubusercontent.com/assets/15053675/24259992/b4bf76d6-0faf-11e7-8a65-e61b0643e86c.png)
![ar view post creation](https://cloud.githubusercontent.com/assets/15053675/24259984/aeaa3db2-0faf-11e7-83ba-77a0a67a78bb.png)

**Comment by ramonski** [comment]
Will be fixed in the new AR Add form
