### ISSUE TITLE
Allow external Python library functions to be used in Calculation Formulas

### ISSUE THREAD

**Issue by ramonski** [bikalabs/bika.lims#1999]
## Steps to reproduce

Create a new Calculation in `bika_setup.bika_calculations`.

## Current behavior

The user can use the functions of the `math` module (prefixed with `math`) or simple arithmetic operators like `+ - / *` etc. 

## Expected behavior

The user should be able to use a function from an external library, e.g. `gammaincinv` from `scipy.special` in the formula.

## Screenshot (optional)

<img width="1079" alt="faserkonzentration_asbest_ _bikalims_-_liscon" src="https://cloud.githubusercontent.com/assets/713193/24375250/f2a2c616-1337-11e7-93d2-783b823063da.png">

**Comment by xispa** [comment]
This one is really cool!. Different approach, but similar result https://jira.bikalabs.com/browse/LIMS-2206

**Comment by ramonski** [comment]
Thanks Jordi, I wasn't aware of LIMS-2206. So we can close 2 Tickets with one PR!

Another cool thing is that you can use now your own functions within calculations.
E.g. you can add a `calculations.py` into `customer.package` and simply use from `customer.package.calculations` the function `awsome` in your awesome calculation😄

Please feel free to review/merge this branch if you have time (think rockfruit will be thankful with his current workload). It is targeted for `master`, so it will be included in bika.lims 3.3
