### ISSUE TITLE
bika.lims 3.1.13 is not compatible with Plone >4.3.11

### ISSUE THREAD

**Issue by tremolo** [bikalabs/bika.lims#2055]
## Steps to reproduce
Install bika.lims with Plone >4.3.11

## Current behavior
registration of bika.lims fails because Plone 4.3.12 switched to DCWorkflow 2.2.5
https://plone.org/download/releases/4.3.12
and bika.lims is not compatible with DCWorkflow 2.2.5

## Traceback
....
  Module collective.wtf.exportimport, line 39, in generateWorkflowXML
....
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
....
 - URL: workflowConfig
   - Line 35, Column 43
   - Expression: <PathExpr standard:u'info/groups'>
   - Names:
      {'container': <collective.wtf.exportimport.CSVWorkflowDefinitionConfigurator object at 0x7fc5195d03d0>,
       'context': <collective.wtf.exportimport.CSVWorkflowDefinitionConfigurator object at 0x7fc5195d03d0>,
       'default': <object object at 0x7fc53af48be0>,
       'here': <collective.wtf.exportimport.CSVWorkflowDefinitionConfigurator object at 0x7fc5195d03d0>,
       'loop': {},
       'nothing': None,
       'options': {'args': (), 'workflow_id': 'bika_inactive_workflow'},
       'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7fc51954d730>,
       'request': <HTTPRequest, URL=http://127.0.0.1:8080/Plone/portal_quickinstaller/installProducts>,
       'root': <Application at >,
       'template': <PageTemplateFile at /Plone/portal_workflow/bika_inactive_workflow/workflowConfig>,
       'user': <PropertiedUser 'admin'>}

## Expected behavior

It should be possible to install bika.lims following the given documentation.
Please update the documentation to clearly state that Plone >4.3.11 is not
compatible or fix the issue.

**Comment by ramonski** [comment]
This issue seem to be related to `collective.wtf`, which was dropped in bika.lims 3.2.1.
Which version are you using and do you encounter the same issue with the latest development branch `master` or `3.2.1`?

**Comment by ramonski** [comment]
Probably we should release a 3.1.14 and pin Plone to 4.3.11

**Comment by ramonski** [comment]
Version 3.1.15 pins Plone to version 4.3.11:
https://pypi.python.org/pypi/bika.lims/3.1.15
