### ISSUE TITLE
Sort order on all landing pages are broken

### ISSUE THREAD

**Issue by lemoene** [bikalabs/bika.lims#2065]
## Steps to reproduce

View any  'Set-up' listing, e.g. https://bikalims.ridingbytes.com/clients, https://bikalims.ridingbytes.com/bika_setup/bika_analysisservices

## Current behavior

Lists are unsorted

## Expected behavior

Normally non-transactional listed items are ordered alphabetically 

## Screenshot (optional)

Same same in https://jira.bikalabs.com/browse/BC-46

**Comment by lemoene** [comment]
re slack diecussion about this ongoing for me ( in chromium)

Hard refreshed, e.g. https://bikalims.ridingbytes.com/bika_setup/bika_analysisservices does not sort
![image](https://user-images.githubusercontent.com/1196034/26982970-6fa4ce16-4d3a-11e7-8cb3-b22c223670f9.png)

or categories, https://bikalims.ridingbytes.com/bika_setup/bika_analysiscategories

![image](https://user-images.githubusercontent.com/1196034/26983010-956676cc-4d3a-11e7-9b9e-9307af55a140.png)

retesting FF...

**Comment by lemoene** [comment]
Nope, same unsorted for me in FF

**Comment by ramonski** [comment]
Don't seem to be an caching issue:

<img width="1430" alt="analyseleistungen_ _bika" src="https://user-images.githubusercontent.com/713193/26983349-c0067c6e-4d3b-11e7-97e9-7b00146c3cff.png">

**Comment by ramonski** [comment]
The issue described by @lemoene is related to https://github.com/bikalabs/bika.lims/pull/1920.

The asynchronous requests coming in for the categories (e.g. for /bikalims/bika_setup/bika_analysisservices) are anonymous. Since the mentioned PR secured the objects to be exactly **not** accessible for anonymous, it is the reason why the sorting is not working anymore.

See the following code excerpt coming from https://github.com/bikalabs/bika.lims/blob/master/bika/lims/controlpanel/bika_analysisservices.py#L304:

```
 299             if not self.context.bika_setup.getShowPrices():
 300                 for i in range(len(self.review_states)):
 301                     self.review_states[i]['columns'].remove('Price')
 302
 303             bsc = getToolByName(self.context, 'bika_setup_catalog')
 304             self.an_cats = bsc.unrestrictedSearchResults(portal_type="AnalysisCategory",
 305                                                          sort_on="sortable_title")
 306
 307             import pdb; pdb.set_trace()
 308
 309  ->         self.an_cats_order = dict([(b.Title, "{:04}".format(a))
 310                                       for a, b in enumerate(self.an_cats)])

(Pdb++) bsc(portal_type="AnalysisCategory", sort_on="sortable_title")
[]
(Pdb++) from plone import api
(Pdb++) api.user.get_current()
<SpecialUser 'Anonymous User'>
(Pdb++) bsc.unrestrictedSearchResults(portal_type="AnalysisCategory", sort_on="sortable_title")
[<Products.ZCatalog.Catalog.mybrains object at 0x10bdb4940>, ...]
```

**Comment by ramonski** [comment]
Possible workaround:
The asynchronous Ajax call has to contain the `__ac` cookie in the request.

**Comment by ramonski** [comment]
Seems like we have **no** authenticated user in a views' `__init__` method. Therefore, no permission relevant content lookups should be done in there.

**Comment by lemoene** [comment]
damn, here is another:

Creating a new order, https://bikalims.ridingbytes.com/clients/client-1/portal_factory/SupplyOrder/supplyorder.2017-06-19.6922120049/edit?_authenticator=790d18c52eaf2f30b962b082629a484f8dcd0fc6

![image](https://user-images.githubusercontent.com/1196034/27301760-b0717f28-5534-11e7-8b41-43f0bb5c8542.png)

**Comment by mikejmets** [comment]
I don't think this is the same issue, the lab products list is fine https://bikalims.ridingbytes.com/bika_setup/bika_labproducts. Also I responded on BC-46 that the reason that Analysis Services order was incorrect was because the Analysis Categories sort order field values were incorrect.

**Comment by ramonski** [comment]
Yes, this is a different issue. I created https://github.com/bikalabs/bika.lims/issues/2105 instead and close this one.
