### ISSUE TITLE
Lists. Display column configuration fails

### ISSUE THREAD

**Issue by lemoene** [bikalabs/bika.lims#2066]
Same as https://jira.bikalabs.com/browse/BC-42

see https://bikalims.ridingbytes.com/batches/B17-001

Basically tihis bit does n ot work, https://demo.bikalabs.com/knowledge-centre/manual/bika-3-user-manual/introduction-and-overview/display-columns.-screen-restrictions

Trying to hide columns by deselecting them does not work. The page refreshes unchanged.
Chromium. did hard refresh

## Steps to reproduce

Right click on any table header and select extra or deselect existing columns for display

## Current behavior

The page refreshes sans changes

## Expected behavior

Only the selected Columns should display

**Comment by mikejmets** [comment]
Looks like a varnish issue. Had the same issue on dev2.mjlims.com until I bypassed varnish ie point nginx to haproxy. Both sites were created with bika_ansible.

**Comment by ramonski** [comment]
Agree with @mikejmets, this might be indeed a Varnish issue, as the sortings should be set as a Cookie. I think this is the related Varnish config that causes the issue in the `bika.ansible` playbook:
https://github.com/bikalabs/bika.ansible/blob/master/roles/bika_varnish/templates/default.vcl.j2#L43
I will check that, and think about a workaround.

**Comment by ramonski** [comment]
Same Issue appears without Varnish.

Seems like the localized strings are used  in the `toggle_cols` Cookie (see Screenshot):

<img width="1716" alt="gerate_" src="https://user-images.githubusercontent.com/713193/27024397-adf85a8e-4f56-11e7-895b-9df8f209ee6d.png">

Thanks to @grulisco for finding this out.

Furthermore, it seems like the Values in the Cookie appear multiple times, which might indicate a bug during Cookie setting. Anyone else having multiple values in this Cookie?

**Comment by mikejmets** [comment]
No duplicates on my instance. ![screenshot from 2017-06-12 10-21-07](https://user-images.githubusercontent.com/231574/27024984-18bab6ee-4f59-11e7-9e28-539283ec1ec5.png)

The weird thing is the cookie values are correct and do change when I select/deselect columns but it has no affect on what gets displayed.

You might what to view cookies on firebug ;-)

**Comment by mikejmets** [comment]
The diff between varnish in and varnish out on my site is not in the contents of the cookie. Without varnish, bika_listing responds to column changes, with varnish it doesn't.

**Comment by ramonski** [comment]
Ok, I'll check the Varnish VCL, just need to reproduce the issue first. But it seems you are right with your assumption, thanks Mike.

**Comment by ramonski** [comment]
On a Varnish enabled site, I still get the localized Values in the Cookie (FF/Chrome):
<img width="673" alt="gerate_" src="https://user-images.githubusercontent.com/713193/27026886-a0a90f6e-4f5f-11e7-9597-b1d020589ca3.png">

**Comment by ramonski** [comment]
Bika LIMS set too many Cookies which does not allow any sanitization in Varnish for the moment.
As long as we do not have a list of Cookies set by Bika LIMS or all Cookies can be matched with a RegEx, e.g. `bika.*`, Varnish won't touch these Cookies anymore.
