### ISSUE TITLE
Priority icon does not save

### ISSUE THREAD

**Issue by lemoene** [bikalabs/bika.lims#2067]
## Steps to reproduce

Upload a new image at https://bikalims.ridingbytes.com/bika_setup/bika_arpriorities/arpriority-2

(to reduce clutter I configure 'Normal' with a transparent icon, only others will satnd out)

## Current behavior

The new image is not saved

## Expected behavior

The new image to be saved and used

**Comment by ramonski** [comment]
Not sure if this is maybe Varnish Cache related. I just created a new Priority "Blocked" and uploaded an icon and it seems to work: https://bikalims.ridingbytes.com/bika_setup/bika_arpriorities/arpriority-5

<img width="923" alt="blocked_ _bika_und_slack_-_bikalims_und___bin_instance_fg__stty_sane__python2_7_" src="https://user-images.githubusercontent.com/713193/27010121-a6251360-4e9d-11e7-97c0-ce94e719a5a9.png">

Could you give some more details about the issue @lemoene?

**Comment by ramonski** [comment]
not reproducable
