### ISSUE TITLE
Member Discount is always applied on adding new ARs

### ISSUE THREAD

**Issue by ramonski** [bikalabs/bika.lims#2068]
## Steps to reproduce

1. Setup Member Discount and VAT in Bika Setup Accounting
2. Add an Analysis Service with a Price (excluding VAT)
3. Add a new AR for a customer w/o Member or Bulk Discount
4. Select the prior created Analysis Service and check the Price

## Screenshot (optional)

<img width="914" alt="bika_setup_" src="https://cloud.githubusercontent.com/assets/713193/26761030/38371918-4928-11e7-882a-426d3683aca7.png">

<img width="921" alt="riding_bytes_" src="https://cloud.githubusercontent.com/assets/713193/26761051/a8260b58-4928-11e7-8da6-d9462086b8d7.png">

<img width="747" alt="rb-test-analyse_" src="https://cloud.githubusercontent.com/assets/713193/26761054/c84f79aa-4928-11e7-8939-6d18dd945790.png">

<img width="820" alt="add_analysis_request_" src="https://cloud.githubusercontent.com/assets/713193/26761090/63da1420-4929-11e7-8992-4dc68c17e036.png">

**Comment by lemoene** [comment]
recreated, a bug, If the client is not set up for membership or bulk prices, they should not apply

**Comment by ramonski** [comment]
IMO the VAT calculation is also not correct, as it should be calculated from the discounted price.

**Comment by ramonski** [comment]
https://github.com/bikalabs/bika.lims/blob/master/bika/lims/browser/js/bika.lims.analysisrequest.add_by_col.js#L2438
