### ISSUE TITLE
Allow non-numeric results in Analysis

### ISSUE THREAD

**Issue by ramonski** [bikalabs/bika.lims#2069]
## Description

Currently only numeric results are allowed for Analyses. However, sometimes it is desired to have textual encoded results, like `3,10,14`, which could describe the results after 1 minute, 5 minutes, 15 minutes. Also more complex result values could be possible.

## Current Behavior

Only numerical Results are possible

## Desired Behavior

Text based Results should be possible as well

## Screenshot

<img width="1149" alt="wasser-0004-r01_" src="https://cloud.githubusercontent.com/assets/713193/26762031/f9c56316-493a-11e7-943f-77ef70c4665c.png">

**Comment by ronna** [comment]
Hi @ramonski I am not sure if this requirement is similar to what you are doing: https://jira.bikalabs.com/browse/HEALTH-566

Its more about the interpretation of the results. If I remember correctly for viral load they is a result value of "Undetectable" which can not be captured as numeric 0 

Sorry I could not respond to your slack over the weekend I was on mobile phone and could not look up the Jira ticket.

**Comment by ronna** [comment]
And this one as well: https://jira.bikalabs.com/browse/HEALTH-579

**Comment by ramonski** [comment]
feature dropped after a discussion with the client, as they will use the results interpretation/analysis remarks field to handle non-numeric results.
