### ISSUE TITLE
AR Templates do not apply Sample Partitions

### ISSUE THREAD

**Issue by lemoene** [bikalabs/bika.lims#2076]
## Steps to reproduce
a la https://jira.bikalabs.com/browse/BC-58, asking Lunga and Mike to assist
_I created an AR template with 2 partitions, https://test2.mjlims.com/bika_setup/bika_artemplates/artemplate-2_

## Current behavior
_When I use it in AR Create, only 1 Partition gets created and all Analyses assigned to it_
![image](https://user-images.githubusercontent.com/1196034/26941729-ca3dd2d4-4c7f-11e7-899c-ca0f2d4ec90d.png)

![image](https://user-images.githubusercontent.com/1196034/26941742-d8e7ec7a-4c7f-11e7-80f5-cb256dab10bf.png)
![image](https://user-images.githubusercontent.com/1196034/26941758-e8c8aff8-4c7f-11e7-9167-0bfa6beab51f.png)

![image](https://user-images.githubusercontent.com/1196034/26941779-f97432b4-4c7f-11e7-8c63-f535bc665925.png)

## Expected behavior

AR Sample is to be created with 2 Partitions and their Analyses assigned as per AR Template

**Comment by lemoene** [comment]
Also AR Manage Analyses tab displays a similar issue, Partitions not offered

![image](https://user-images.githubusercontent.com/1196034/26947823-54f1b396-4c94-11e7-9455-20d99bce9dab.png)

To add Sample Partitions to an existing AR, remember it can only be done on the *Partitions tab on the Sample* itself. Where it rightfully belongs. Took me a while to find though;-)

![image](https://user-images.githubusercontent.com/1196034/26947889-a329828c-4c94-11e7-8164-06137091584f.png)

**Comment by mikejmets** [comment]
Looks like a varnish issue. Had the same issue on dev2.mjlims.com until I bypassed varnish ie point nginx to haproxy. Both sites were created with bika_ansible and I'd like to know of other sites I can test on.

**Comment by mikejmets** [comment]
Fixed see https://github.com/bikalabs/bika.lims/pull/2081
