### ISSUE TITLE
Bika Listing display columns uses localized column headers in Cookie

### ISSUE THREAD

**Issue by ramonski** [bikalabs/bika.lims#2089]
## Steps to reproduce

1. Switch your browser to German language
2. View a listing, e.g. Instruments
3. Right-click on the Header column (neither toggle logic nor check-marks are working correctly, see screenshot 1)

Do the same

## Current behavior

Neither toggle is working nor the check-marks are displayed properly.

## Expected behavior

Display columns work independently from localization

## Screenshot (optional)

Screenshot 1 (German language on FF):
<img width="1229" alt="gerate_ _bika" src="https://user-images.githubusercontent.com/713193/27033036-c8ac6624-4f77-11e7-8063-08eadd89e833.png">

Screenshot 2 (English language on FF):
<img width="1230" alt="instruments_ _bika" src="https://user-images.githubusercontent.com/713193/27033086-0a1ccf68-4f78-11e7-863f-5f79451362d5.png">

**Comment by ramonski** [comment]
Also related to https://github.com/bikalabs/bika.lims/issues/2066

**Comment by mikejmets** [comment]
I set the browser language on ff to DE and when selecting/deselecting, I cannot switch some columns on. This is on Instruments. But all those that are selectable do render correctly.  

![screenshot from 2017-06-12 15-24-30](https://user-images.githubusercontent.com/231574/27036250-8b3e6afa-4f84-11e7-9144-a137ce3add56.png)
