### ISSUE TITLE
Redundant Bika AR List filter buttons should not be displayed

### ISSUE THREAD

**Issue by lemoene** [bikalabs/bika.lims#2094]
Towards cleaner UI, Please display list filters to correspond with Bika Setup

e.g. _**To be Sampled**_ and _**Scheduled Sampling**_ filter buttons do not have to be displayed if deselected in the Bika set-up

_**Preservation**_ is handled per Sample, but we could toggle this off completely in the Set-up too, e.g. ALS does not use it. This could defo have further knock-ons, and cam be left as is for now

## Steps to reproduce

Navigate to any AR list, say https://bikalims.ridingbytes.com/analysisrequests

![image](https://user-images.githubusercontent.com/1196034/27078846-9808cca6-5035-11e7-8718-ba15a5179ff3.png)

**Comment by mikejmets** [comment]
@lemoene  please confirm:
3 buttons on AR listing and their relationship to bika_setup:
To be Sampled: related Enable Sampling
To be Preserved: new bika_setup field?
Scheduled Sampling: related Enable Sampling Scheduling

**Comment by lemoene** [comment]
_To be Preserved: new bika_setup field?_

Yes, i think put it on the new Sampling and COC tab too, "Enable Sample Preservation"

BTW, just spotted: Could you change _coc_ in the tab title to _COC_ in capitals please.

**Comment by lemoene** [comment]
Please make "Enable Sample Preservation" the 4th option on the page, just before "Default sample retention period". thanks

**Comment by ramonski** [comment]
should be done with the PR from @Lunga001.
