### ISSUE TITLE
Importing Instrument results

### ISSUE THREAD

**Issue by Lunga001** [bikalabs/bika.lims#2115]
## Steps to reproduce
    Create an AR
    Go to an AS that's on the AR and change the Keyword
    Choose an instrument to work with
    Run the Instrument import for that AR with the new Keyword
    And you should get an error message saying
    No analyses found for {AR} and {Keyword}

## Current behavior
     If you edit the AS keyword associated with an existing AR, the AR analyses(getAnalyses) does not 
     get updated with the new keyword as it shows the old value of the AS keyword

## Expected behavior
     The Instrument Import results should match the AR and the new AS keyword

**Comment by lemoene** [comment]
As per Slack:

Not a bug lungab, true to spec - setup items are all versioned to conserve db integrity. All mods to setup items result in new versions and historic transactions keep referencing the older versions used at object creation. Eg, you don't want AS price changes to reflect on old ARs. Always create new ARs to test with after editing ASs. Caught me out yesterday too (again)
