### ISSUE TITLE
Default Container (Improvement Request)

### ISSUE THREAD

**Issue by eshiet** [bikalabs/bika.lims#2147]
## Current behavior
In creating an analysis request, when someone selects the sample type the default container for the container is empty i.e it doesn't automatically select the default container of the sample type.
## Expected behavior
When someone selects the sample type during analysis request creation, the default container should automatically be filled in the default container option.
## Screenshot (optional)
![screenshot from 2017-07-24 05 27 07](https://user-images.githubusercontent.com/13769435/28508200-281a54ca-7031-11e7-9eb3-b8aaa1ff6c57.png)

**Comment by ramonski** [comment]
Thanks for adding this issue @eshiet.
The AR Add form is currently under complete rework for `3.2.1`.
Besides other great features like full clone support and dependency checking, it will also have a better partition, container and preservation handling. Please stay tuned for the coming release.
Best Regards, Ramon

**Comment by ramonski** [comment]
will be implemented in the new AR Add form (coming soon)
